const FrontendLinks = {
    home: "/",
    mainWebsite: "https://lendsqr.com/",
    // auth
    login: "/auth/login",
    register: "/auth/register",
    forgotPassword: "/auth/forgot-password",
    // dashboard
    dashboard: "/dashboard",
    // customers
    users: "/dashboard/users",
    userDetails: (id: string) => `/dashboard/users/${id}`,
    guarantors: "/dashboard/guarantors",
    guarantorDetails: (id: string) => `/dashboard/guarantors/${id}`,
    loans: "/dashboard/loans",
    loanDetails: (id: string) => `/dashboard/loans/${id}`,
    decisionModels: "/dashboard/decision-models",
    decisionModelDetails: (id: string) => `/dashboard/decision-models/${id}`,
    savings: "/dashboard/savings",
    savingsDetails: (id: string) => `/dashboard/savings/${id}`,
    loanRequests: "/dashboard/loan-requests",
    loanRequestDetails: (id: string) => `/dashboard/loan-requests/${id}`,
    whitelist: "/dashboard/whitelist",
    karma: "/dashboard/karma",
    borrowers: "/dashboard/borrowers",
    borrowerDetails: (id: string) => `/dashboard/borrowers/${id}`,
    // businesses
    organization: "/dashboard/organization",
    organizationDetails: (id: string) => `/dashboard/organization/${id}`,
    loanProducts: "/dashboard/loan-products",
    loanProductDetails: (id: string) => `/dashboard/loan-products/${id}`,
    savingsProducts: "/dashboard/savings-products",
    savingsProductDetails: (id: string) => `/dashboard/savings-products/${id}`,
    feesCharges: "/dashboard/fees-charges",
    feeDetails: (id: string) => `/dashboard/fees-charges/${id}`,
    transactions: "/dashboard/transactions",
    transactionDetails: (id: string) => `/dashboard/transactions/${id}`,
    services: "/dashboard/services",
    serviceDetails: (id: string) => `/dashboard/services/${id}`,
    serviceAccount: "/dashboard/service-account",
    settlements: "/dashboard/settlements",
    settlementDetails: (id: string) => `/dashboard/settlements/${id}`,
    reports: "/dashboard/reports",
    reportDetails: (id: string) => `/dashboard/reports/${id}`,
    // settings
    preferences: "/dashboard/preferences",
    feesPricing: "/dashboard/fees-pricing",
    auditLogs: "/dashboard/audit-logs",
    auditLogDetails: (id: string) => `/dashboard/audit-logs/${id}`,
    systemsMessages: "/dashboard/systems-messages",
    systemMessageDetails: (id: string) => `/dashboard/systems-messages/${id}`,
}

export default FrontendLinks;